# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foxyproxy < Formula
  desc "fxpr is a CLI tool to quickly spin up and destroy DigitalOcean servers"
  homepage "https://github.com/elnoro/foxyproxy"
  version "0.1.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elnoro/foxyproxy/releases/download/v0.1.2/foxyproxy_0.1.2_darwin_arm64.tar.gz"
      sha256 "3e25cbd033c84ad31848ac43cafbcd0b907474238bfd12ac885ebfa0a2150f0d"

      def install
        bin.install "fxpr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elnoro/foxyproxy/releases/download/v0.1.2/foxyproxy_0.1.2_darwin_amd64.tar.gz"
      sha256 "775064d72f11abd2e7d807532660d780d1602ed1f9b8b809d6863de1b3902393"

      def install
        bin.install "fxpr"
      end
    end
  end
end
