# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foxyshot < Formula
  desc "A lightweight tool to upload MacOS screenshots to an S3-compatible provider"
  homepage "https://github.com/elnoro/foxyshot"
  version "0.1.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elnoro/foxyshot/releases/download/v0.1.3/foxyshot_0.1.3_darwin_arm64.tar.gz"
      sha256 "d9dc3d17f1cbc86b2de40f18a52a31561efb0d2d9b1e000f70c77301fb7a2614"

      def install
        bin.install "foxyshot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elnoro/foxyshot/releases/download/v0.1.3/foxyshot_0.1.3_darwin_amd64.tar.gz"
      sha256 "1fcea98005081d2d8ed8ea4a052a3816a1e77b8dca5a2b8330aa1985bce728ab"

      def install
        bin.install "foxyshot"
      end
    end
  end

  service do
    run: foxyshot run
  end
end
