# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foxyproxy < Formula
  desc "fxpr is a CLI tool to quickly spin up and destroy DigitalOcean servers"
  homepage "https://github.com/elnoro/foxyproxy"
  version "0.1.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elnoro/foxyproxy/releases/download/v0.1.3/foxyproxy_0.1.3_darwin_arm64.tar.gz"
      sha256 "cdb9b3b1abee44c13f2666de0195f02ea0f69c23757bad548552bedee1f6dc3a"

      def install
        bin.install "fxpr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elnoro/foxyproxy/releases/download/v0.1.3/foxyproxy_0.1.3_darwin_amd64.tar.gz"
      sha256 "8648037ba691d40f4ae572753dad41ce7c501290c7b508439e2320acde7d6934"

      def install
        bin.install "fxpr"
      end
    end
  end
end
