# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foxyproxy < Formula
  desc "fxpr is a CLI tool to quickly spin up and destroy DigitalOcean servers"
  homepage "https://github.com/elnoro/foxyproxy"
  version "0.1.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elnoro/foxyproxy/releases/download/v0.1.3/foxyproxy_0.1.3_darwin_arm64.tar.gz"
      sha256 "9880d49d0e49649c013a4704f34e66401ce1bc69d60e5d9b78e4eba2892b2bba"

      def install
        bin.install "fxpr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elnoro/foxyproxy/releases/download/v0.1.3/foxyproxy_0.1.3_darwin_amd64.tar.gz"
      sha256 "88d076bb0a8118ecce8f37c94316e3b784480262cb877620a7921a5e92748391"

      def install
        bin.install "fxpr"
      end
    end
  end
end
