# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foxyshot < Formula
  desc "A lightweight tool to upload MacOS screenshots to an S3-compatible provider"
  homepage "https://github.com/elnoro/foxyshot"
  version "0.1.9"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elnoro/foxyshot/releases/download/v0.1.9/foxyshot_0.1.9_darwin_arm64.tar.gz"
      sha256 "1a735747615636f6cd622480ef904a22a6e802fb8d7e490710b69d6a818edd34"

      def install
        bin.install "foxyshot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elnoro/foxyshot/releases/download/v0.1.9/foxyshot_0.1.9_darwin_amd64.tar.gz"
      sha256 "9f158d6052c8e914cdee048ea8231ab9055e50525c398738f3d2ea8ce01ee213"

      def install
        bin.install "foxyshot"
      end
    end
  end

  service do
    run [opt_bin/"foxyshot", "run", "-logfile", opt_prefix/"foxyshot.log"]
  end
end
